### PR TITLE
Created all routes

### PR DESCRIPTION
**Pull request by jabrake**
- Created all GET, POST and PUT routes
- Sending back appropriate status code (and message if relevant/possible)

@tchitrakorn @farhanali3193 for review, thanks!

### CODE REVIEW

**Review by tchitrakorn — APPROVED** [review]
Hi @jabrake, looks good to me! I'm assuming that all status codes that you return are based off the ones in the original API? I didn't realize that the default sorting option is "newest" before for /reviews endpoint, but if that was specified somewhere then this looks great. I will go ahead and merge then!

**Comment by jabrake** [comment]
Thanks @tchitrakorn! Yes the status codes are what the API is expecting (for a successful request, I'll have to add the error statuses later). I also completely made up that default sort option just to test that all the parameters were coming through - the default isn't specified in the API docs so I'm not sure if there even is a default! Do you remember what sort order the API would return if you didn't include a sort parameter in the request?

**Comment by farhanali3193** [comment]
@jabrake : I think this is a new addition. I remember my front end didn't need to pass in a sort parameter. Correct me if I am wrong @tchitrakorn. For the front end, the default was supposed to be 'relevant'.

**Comment by tchitrakorn** [comment]
@farhanali3193 Ah yes, you're right. Now that you mentioned it I don't think "sort" is one of the parameters (unless they've changed it). The sorting is done completely in the front-end, so my guess is that @jabrake you can just remove the "sort" parameter. Very sorry that I have already merged this PR to your main, but hopefully the change is minimal enough that it won't cause any problems.

**Comment by farhanali3193** [comment]
@jabrake @tchitrakorn : Just checked Learn and they have actually changed it. So now the Front end is supposed to send a "sort" parameter.

**Comment by tchitrakorn** [comment]
@farhanali3193 Got it! Sorry I was confused earlier. Does that mean that the sorting is done in the backend now instead of front end?

**Comment by farhanali3193** [comment]
@tchitrakorn That's what I am thinking. So I guess more work for Jorge.

**Comment by jabrake** [comment]
Haha I guess that's why they changed it 🙃 for now it's totally fine though! My code currently accounts for a "sort" parameter coming from the client and if there isn't, setting a default. So for now no changes - but I guess I'll eventually have to figure out how to sort the response 😄

**Pull request merged**
